# Notebook Purpose

The purpose of this Jupyter notebook is to explore the DUD-E GPCR dataset. We explore both the raw (CSV) dataset as well as the processed (PKL) datasets.

## Imports

Import any modules requires.

In [1]:
import sys
from pathlib import Path

# make the project root importable so the `datasets` package resolves
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from eda.helpers import *
from datasets.dataset_handler import DatasetHandler
from datasets.enums import DatasetSource, FeatureType

## Attributes

In [2]:
handler = DatasetHandler()
dataset_source = DatasetSource.DUDE_GPCR

## Raw CSV

Explore the raw CSV file after loading it into a Pandas DataFrame.

In [3]:
raw_df = handler.load_raw_dataset(
    dataset_source=dataset_source
)

In [4]:
explore_df(df=raw_df)

Shape: 99,782 rows x 6 columns

Info:
<class 'pandas.DataFrame'>
RangeIndex: 99782 entries, 0 to 99781
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   smiles  99782 non-null  str
 1   adrb1   16097 non-null  float64
 2   adrb2   15231 non-null  float64
 3   aa2ar   32032 non-null  float64
 4   drd3    34530 non-null  float64
 5   cxcr4   3446 non-null   float64
dtypes: float64(5), str(1)
memory usage: 4.6 MB

Describe:

,smiles,adrb1,adrb2,aa2ar,drd3,cxcr4
count,99782,16097.000000,15231.000000,32032.000000,34530.000000,3446.000000
unique,99782,NaN,NaN,NaN,NaN,NaN
top,C#CC(=O)NC1CC(C1)[NH3+],NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN
mean,NaN,0.015344,0.015166,0.015047,0.013901,0.011608
std,NaN,0.122923,0.122219,0.121744,0.117082,0.107127
min,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
75%,NaN,0.000000,0.000000,0.000000,0.000000,0.000000
max,NaN,1.000000,1.000000,1.000000,1.000000,1.000000

Sample:

,smiles,adrb1,adrb2,aa2ar,drd3,cxcr4
0,C#CC(=O)NC1CC(C1)[NH3+],NaN,NaN,NaN,0.0,NaN
1,C#CCN(C1CCCCC1)C(=O)C[C@H]2C(=O)NCC[NH+]2Cc3cc...,NaN,NaN,NaN,0.0,NaN
2,C#CCN(C1CCCCC1)C(=O)Nc2cccc(c2)N3CCNC3=O,NaN,NaN,0.0,NaN,NaN
3,C#CCN(Cc1cc(cc2c1OCOC2)[N+](=O)[O-])[C@@H]3CCc...,NaN,NaN,0.0,NaN,NaN
4,C#CCN(Cc1ccco1)C(=O)C(=O)Nc2ccc(cc2)Oc3ccccc3C#N,NaN,NaN,NaN,0.0,NaN

In [5]:
check_nulls(df=raw_df, column="smiles")

Column: smiles
Nulls: 0 of 99,782 rows (0.00%)
Non-null: 99,782

## Processed PKL files

Display and look at the processed PKL files created.

### ECFP Fingerprint

In [6]:
ecfp_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.ECFP)
show_df(df=ecfp_df)
show_first_value(df=ecfp_df, column="mol")

,smiles,adrb1,adrb2,aa2ar,drd3,cxcr4,mol
0,C#CC(=O)NC1CC(C1)[NH3+],NaN,NaN,NaN,0.0,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,C#CCN(C1CCCCC1)C(=O)C[C@H]2C(=O)NCC[NH+]2Cc3cc...,NaN,NaN,NaN,0.0,NaN,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,C#CCN(C1CCCCC1)C(=O)Nc2cccc(c2)N3CCNC3=O,NaN,NaN,0.0,NaN,NaN,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,C#CCN(Cc1cc(cc2c1OCOC2)[N+](=O)[O-])[C@@H]3CCc...,NaN,NaN,0.0,NaN,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,C#CCN(Cc1ccco1)C(=O)C(=O)Nc2ccc(cc2)Oc3ccccc3C#N,NaN,NaN,NaN,0.0,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,C#CCN(Cc1ccco1)CC(=O)Nc2cc(nn2c3ccccc3)C4CC4,NaN,NaN,NaN,0.0,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,C#CCN1C(=O)/C(=C\c2cc(c(c(c2)Cl)O)Cl)/SC1=O,NaN,NaN,NaN,0.0,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,C#CCN1CCCC[C@H]1C(=O)N2CCN(CC2)Cc3cc(=O)n4ccsc...,NaN,NaN,NaN,0.0,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,C#CCNC(=O)CCNC(=O)NCC1(CCCCC1)[NH+]2CCCCC2,NaN,0.0,NaN,NaN,NaN,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,C#CCNC(=O)CCNC(=O)NCCC[NH+]1CCN(CC1)Cc2ccccc2,0.0,NaN,NaN,NaN,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

mol: [0. 0. 0. ... 0. 0. 0.]

### DGL

In [7]:
dgl_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.DGL)
show_df(df=dgl_df)
show_first_value(df=dgl_df, column="mol")

,smiles,adrb1,adrb2,aa2ar,drd3,cxcr4,mol
0,C#CC(=O)NC1CC(C1)[NH3+],NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=10, num_edges=30,\n ndata..."
1,C#CCN(C1CCCCC1)C(=O)C[C@H]2C(=O)NCC[NH+]2Cc3cc...,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=27, num_edges=85,\n ndata..."
2,C#CCN(C1CCCCC1)C(=O)Nc2cccc(c2)N3CCNC3=O,NaN,NaN,0.0,NaN,NaN,"Graph(num_nodes=25, num_edges=79,\n ndata..."
3,C#CCN(Cc1cc(cc2c1OCOC2)[N+](=O)[O-])[C@@H]3CCc...,NaN,NaN,0.0,NaN,NaN,"Graph(num_nodes=27, num_edges=87,\n ndata..."
4,C#CCN(Cc1ccco1)C(=O)C(=O)Nc2ccc(cc2)Oc3ccccc3C#N,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=30, num_edges=94,\n ndata..."
5,C#CCN(Cc1ccco1)CC(=O)Nc2cc(nn2c3ccccc3)C4CC4,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=28, num_edges=90,\n ndata..."
6,C#CCN1C(=O)/C(=C\c2cc(c(c(c2)Cl)O)Cl)/SC1=O,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=20, num_edges=62,\n ndata..."
7,C#CCN1CCCC[C@H]1C(=O)N2CCN(CC2)Cc3cc(=O)n4ccsc...,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=28, num_edges=90,\n ndata..."
8,C#CCNC(=O)CCNC(=O)NCC1(CCCCC1)[NH+]2CCCCC2,NaN,0.0,NaN,NaN,NaN,"Graph(num_nodes=25, num_edges=77,\n ndata..."
9,C#CCNC(=O)CCNC(=O)NCCC[NH+]1CCN(CC1)Cc2ccccc2,0.0,NaN,NaN,NaN,NaN,"Graph(num_nodes=28, num_edges=86,\n ndata..."

mol: Graph(num_nodes=10, num_edges=30,
      ndata_schemes={'feats': Scheme(shape=(177,), dtype=torch.float32)}
      edata_schemes={})

### DGL with bonds

In [8]:
dgl_bonds_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.DGL_WITH_BONDS)
show_df(df=dgl_bonds_df)
show_first_value(df=dgl_bonds_df, column="mol")

,smiles,adrb1,adrb2,aa2ar,drd3,cxcr4,mol
0,C#CC(=O)NC1CC(C1)[NH3+],NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=10, num_edges=30,\n ndata..."
1,C#CCN(C1CCCCC1)C(=O)C[C@H]2C(=O)NCC[NH+]2Cc3cc...,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=27, num_edges=85,\n ndata..."
2,C#CCN(C1CCCCC1)C(=O)Nc2cccc(c2)N3CCNC3=O,NaN,NaN,0.0,NaN,NaN,"Graph(num_nodes=25, num_edges=79,\n ndata..."
3,C#CCN(Cc1cc(cc2c1OCOC2)[N+](=O)[O-])[C@@H]3CCc...,NaN,NaN,0.0,NaN,NaN,"Graph(num_nodes=27, num_edges=87,\n ndata..."
4,C#CCN(Cc1ccco1)C(=O)C(=O)Nc2ccc(cc2)Oc3ccccc3C#N,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=30, num_edges=94,\n ndata..."
5,C#CCN(Cc1ccco1)CC(=O)Nc2cc(nn2c3ccccc3)C4CC4,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=28, num_edges=90,\n ndata..."
6,C#CCN1C(=O)/C(=C\c2cc(c(c(c2)Cl)O)Cl)/SC1=O,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=20, num_edges=62,\n ndata..."
7,C#CCN1CCCC[C@H]1C(=O)N2CCN(CC2)Cc3cc(=O)n4ccsc...,NaN,NaN,NaN,0.0,NaN,"Graph(num_nodes=28, num_edges=90,\n ndata..."
8,C#CCNC(=O)CCNC(=O)NCC1(CCCCC1)[NH+]2CCCCC2,NaN,0.0,NaN,NaN,NaN,"Graph(num_nodes=25, num_edges=77,\n ndata..."
9,C#CCNC(=O)CCNC(=O)NCCC[NH+]1CCN(CC1)Cc2ccccc2,0.0,NaN,NaN,NaN,NaN,"Graph(num_nodes=28, num_edges=86,\n ndata..."

mol: Graph(num_nodes=10, num_edges=30,
      ndata_schemes={'feats': Scheme(shape=(177,), dtype=torch.float32)}
      edata_schemes={'edge_feats': Scheme(shape=(17,), dtype=torch.float32)})