# Notebook Purpose

The purpose of this Jupyter notebook is to explore the MUV dataset. We explore both the raw (CSV) dataset as well as the processed (PKL) datasets.

## Imports

Import any modules requires.

In [1]:
import sys
from pathlib import Path

# make the project root importable so the `datasets` package resolves
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from eda.helpers import *
from datasets.dataset_handler import DatasetHandler
from datasets.enums import DatasetSource, FeatureType

## Attributes

In [2]:
handler = DatasetHandler()
dataset_source = DatasetSource.MUV

## Raw CSV

Explore the raw CSV file after loading it into a Pandas DataFrame.

In [3]:
raw_df = handler.load_raw_dataset(
    dataset_source=dataset_source
)

In [4]:
explore_df(df=raw_df)

Shape: 93,087 rows x 19 columns

Info:
<class 'pandas.DataFrame'>
RangeIndex: 93087 entries, 0 to 93086
Data columns (total 19 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MUV-466  14841 non-null  float64
 1   MUV-548  14734 non-null  float64
 2   MUV-600  14728 non-null  float64
 3   MUV-644  14623 non-null  float64
 4   MUV-652  14902 non-null  float64
 5   MUV-689  14601 non-null  float64
 6   MUV-692  14644 non-null  float64
 7   MUV-712  14411 non-null  float64
 8   MUV-713  14836 non-null  float64
 9   MUV-733  14682 non-null  float64
 10  MUV-737  14691 non-null  float64
 11  MUV-810  14644 non-null  float64
 12  MUV-832  14667 non-null  float64
 13  MUV-846  14711 non-null  float64
 14  MUV-852  14651 non-null  float64
 15  MUV-858  14774 non-null  float64
 16  MUV-859  14746 non-null  float64
 17  mol_id   93087 non-null  str
 18  smiles   93087 non-null  str
dtypes: float64(17), str(2)
memory usage: 13.5 MB

Describe:

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles
count,14841.000000,14734.000000,14728.000000,14623.000000,14902.000000,14601.000000,14644.000000,14411.000000,14836.000000,14682.000000,14691.000000,14644.000000,14667.000000,14711.000000,14651.000000,14774.000000,14746.000000,93087,93087
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93087,93087
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1
mean,0.001819,0.001968,0.002037,0.002052,0.001946,0.001986,0.002049,0.001943,0.001955,0.001907,0.001974,0.001980,0.002045,0.002039,0.001979,0.001963,0.001628,NaN,NaN
std,0.042616,0.044323,0.045088,0.045249,0.044073,0.044524,0.045217,0.044038,0.044170,0.043630,0.044387,0.044458,0.045181,0.045114,0.044448,0.044263,0.040312,NaN,NaN
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,NaN

Sample:

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O

In [5]:
check_nulls(df=raw_df, column="smiles")

Column: smiles
Nulls: 0 of 93,087 rows (0.00%)
Non-null: 93,087

## Processed PKL files

Display and look at the processed PKL files created.

### ECFP Fingerprint

In [6]:
ecfp_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.ECFP)
show_df(df=ecfp_df)
show_first_value(df=ecfp_df, column="mol")

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles,mol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID2999671,CCn1c(CSc2nccn2C)nc2cc(C(=O)O)ccc21,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,CID5390007,CCc1cccc2c1NC(=O)C21C2C(=O)N(Cc3ccccc3)C(=O)C2...,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CID5390006,COc1ccc(C2C(C(=O)NCc3ccccc3)=C(C)N=C3N=CNN32)c...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999674,CCCc1cc(=O)nc(SCC(=O)N(CC(C)C)C2CCS(=O)(=O)C2)...,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999675,CCn1cnc2c1c(=O)n(CC(=O)Nc1cc(C)on1)c(=O)n2Cc1c...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

mol: [0. 0. 0. ... 0. 0. 0.]

### DGL

In [7]:
dgl_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.DGL)
show_df(df=dgl_df)
show_first_value(df=dgl_df, column="mol")

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles,mol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C,"Graph(num_nodes=26, num_edges=86,\n ndata..."
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1,"Graph(num_nodes=24, num_edges=76,\n ndata..."
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...,"Graph(num_nodes=34, num_edges=112,\n ndat..."
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...,"Graph(num_nodes=27, num_edges=87,\n ndata..."
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O,"Graph(num_nodes=15, num_edges=45,\n ndata..."
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID2999671,CCn1c(CSc2nccn2C)nc2cc(C(=O)O)ccc21,"Graph(num_nodes=22, num_edges=70,\n ndata..."
6,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,CID5390007,CCc1cccc2c1NC(=O)C21C2C(=O)N(Cc3ccccc3)C(=O)C2...,"Graph(num_nodes=31, num_edges=103,\n ndat..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CID5390006,COc1ccc(C2C(C(=O)NCc3ccccc3)=C(C)N=C3N=CNN32)c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."
8,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999674,CCCc1cc(=O)nc(SCC(=O)N(CC(C)C)C2CCS(=O)(=O)C2)...,"Graph(num_nodes=26, num_edges=80,\n ndata..."
9,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999675,CCn1cnc2c1c(=O)n(CC(=O)Nc1cc(C)on1)c(=O)n2Cc1c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."

mol: Graph(num_nodes=26, num_edges=86,
      ndata_schemes={'feats': Scheme(shape=(177,), dtype=torch.float32)}
      edata_schemes={})

### DGL with bonds

In [8]:
dgl_bonds_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.DGL_WITH_BONDS)
show_df(df=dgl_bonds_df)
show_first_value(df=dgl_bonds_df, column="mol")

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles,mol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C,"Graph(num_nodes=26, num_edges=86,\n ndata..."
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1,"Graph(num_nodes=24, num_edges=76,\n ndata..."
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...,"Graph(num_nodes=34, num_edges=112,\n ndat..."
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...,"Graph(num_nodes=27, num_edges=87,\n ndata..."
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O,"Graph(num_nodes=15, num_edges=45,\n ndata..."
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID2999671,CCn1c(CSc2nccn2C)nc2cc(C(=O)O)ccc21,"Graph(num_nodes=22, num_edges=70,\n ndata..."
6,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,CID5390007,CCc1cccc2c1NC(=O)C21C2C(=O)N(Cc3ccccc3)C(=O)C2...,"Graph(num_nodes=31, num_edges=103,\n ndat..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CID5390006,COc1ccc(C2C(C(=O)NCc3ccccc3)=C(C)N=C3N=CNN32)c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."
8,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999674,CCCc1cc(=O)nc(SCC(=O)N(CC(C)C)C2CCS(=O)(=O)C2)...,"Graph(num_nodes=26, num_edges=80,\n ndata..."
9,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999675,CCn1cnc2c1c(=O)n(CC(=O)Nc1cc(C)on1)c(=O)n2Cc1c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."

mol: Graph(num_nodes=26, num_edges=86,
      ndata_schemes={'feats': Scheme(shape=(177,), dtype=torch.float32)}
      edata_schemes={'edge_feats': Scheme(shape=(17,), dtype=torch.float32)})