# Notebook Purpose

EDA on how to generate training/testing tasks (from the experimental assays) given the different feature types.

We experiment with the MUV dataset but same would apply with the other datasets.

## Imports

Import any packages required.

In [1]:
import sys
from pathlib import Path

# make the project root importable so the `datasets` package resolves
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from eda.helpers import *
from datasets.dataset_handler import DatasetHandler
from datasets.enums import DatasetSource, FeatureType

## Attributes

Attributes required. As explained in the notebook header, we will attempt this with the MUV dataset for all the different feature types.

This will allow us to understand how test & train tasks are created (depending on the feature types) and will allow us to create a generic process that can be used to create these (agnostic of the dataset source).

In [2]:
test_assays_map = {
    DatasetSource.TOX21: ["SR-HSE", "SR-MMP", "SR-p53"],
    DatasetSource.MUV: ["MUV-832", "MUV-846", "MUV-852", "MUV-858", "MUV-859"],
}

handler = DatasetHandler()
dataset_source = DatasetSource.MUV

## Core Logic

Core logic to generate train/test sets - dependence on the feature type chosen.

### ECFP Fingerprint

In [3]:
ecfp_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.ECFP)
show_df(ecfp_df)

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles,mol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID2999671,CCn1c(CSc2nccn2C)nc2cc(C(=O)O)ccc21,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,CID5390007,CCc1cccc2c1NC(=O)C21C2C(=O)N(Cc3ccccc3)C(=O)C2...,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, ..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CID5390006,COc1ccc(C2C(C(=O)NCc3ccccc3)=C(C)N=C3N=CNN32)c...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999674,CCCc1cc(=O)nc(SCC(=O)N(CC(C)C)C2CCS(=O)(=O)C2)...,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999675,CCn1cnc2c1c(=O)n(CC(=O)Nc1cc(C)on1)c(=O)n2Cc1c...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

Get the testing tasks (assays) depending on the dataset.

In [4]:
test_assays = test_assays_map.get(dataset_source)
print("Test assays for MUV dataset source:", test_assays)

Test assays for MUV dataset source: ['MUV-832', 'MUV-846', 'MUV-852', 'MUV-858', 'MUV-859']

Get the training tasks (assays) by getting the rest of assays that are not inside the testing set.

In [5]:
columns_to_drop = test_assays.copy()
columns_to_drop.extend(["mol_id", "smiles", "mol"])
print("Columns to drop:", columns_to_drop)

train_assays = [x for x in list(ecfp_df.columns) if x not in columns_to_drop]
print("Training assays for MUV dataset:", train_assays)

Columns to drop: ['MUV-832', 'MUV-846', 'MUV-852', 'MUV-858', 'MUV-859', 'mol_id', 'smiles', 'mol']
Training assays for MUV dataset: ['MUV-466', 'MUV-548', 'MUV-600', 'MUV-644', 'MUV-652', 'MUV-689', 'MUV-692', 'MUV-712', 'MUV-713', 'MUV-733', 'MUV-737', 'MUV-810']

For each assay in the training set, filter out NULLs (NULLs mean that there was no test against that assay for that particular molecule).

In [6]:
train_assays_dict = dict.fromkeys(train_assays)
print("Training assays dictionary:", train_assays_dict)

for assay in train_assays:
    task_df = ecfp_df[[assay, 'mol']].dropna()
    task_df.columns = ['y', 'mol'] # y is the target and mol is the molecular embedding (in this case ECFP)

    # show_df(task_df)

    train_assays_dict[assay] = task_df

print("\nPrinting the length of the DataFrame for each assay (in the training set)...")
for assay, assay_df in train_assays_dict.items():
    print(f"Assay: '{assay}' - DataFrame size: '{len(assay_df)}'")

print("\nPrinting active/inactive counts for each assay (in the training set)...")
for assay, assay_df in train_assays_dict.items():
    assay_value_counts = assay_df["y"].value_counts()
    active_count = assay_value_counts.get(1.0, 0)
    inactive_count = assay_value_counts.get(0.0, 0)

    print(f"Assay: '{assay}'; Active: '{active_count}'; Inactive: '{inactive_count}'")

Training assays dictionary: {'MUV-466': None, 'MUV-548': None, 'MUV-600': None, 'MUV-644': None, 'MUV-652': None, 'MUV-689': None, 'MUV-692': None, 'MUV-712': None, 'MUV-713': None, 'MUV-733': None, 'MUV-737': None, 'MUV-810': None}

Printing the length of the DataFrame for each assay (in the training set)...
Assay: 'MUV-466' - DataFrame size: '14841'
Assay: 'MUV-548' - DataFrame size: '14734'
Assay: 'MUV-600' - DataFrame size: '14728'
Assay: 'MUV-644' - DataFrame size: '14623'
Assay: 'MUV-652' - DataFrame size: '14902'
Assay: 'MUV-689' - DataFrame size: '14601'
Assay: 'MUV-692' - DataFrame size: '14644'
Assay: 'MUV-712' - DataFrame size: '14411'
Assay: 'MUV-713' - DataFrame size: '14836'
Assay: 'MUV-733' - DataFrame size: '14682'
Assay: 'MUV-737' - DataFrame size: '14691'
Assay: 'MUV-810' - DataFrame size: '14644'

Printing active/inactive counts for each assay (in the training set)...
Assay: 'MUV-466'; Active: '27'; Inactive: '14814'
Assay: 'MUV-548'; Active: '29'; Inactive: '14705'
Assay: 'MUV-600'; Active: '30'; Inactive: '14698'
Assay: 'MUV-644'; Active: '30'; Inactive: '14593'
Assay: 'MUV-652'; Active: '29'; Inactive: '14873'
Assay: 'MUV-689'; Active: '29'; Inactive: '14572'
Assay: 'MUV-692'; Active: '30'; Inactive: '14614'
Assay: 'MUV-712'; Active: '28'; Inactive: '14383'
Assay: 'MUV-713'; Active: '29'; Inactive: '14807'
Assay: 'MUV-733'; Active: '28'; Inactive: '14654'
Assay: 'MUV-737'; Active: '29'; Inactive: '14662'
Assay: 'MUV-810'; Active: '29'; Inactive: '14615'

And do the same for the assays in the test set.

In [7]:
test_assays_dict = dict.fromkeys(test_assays)
print("Testing assays dictionary:", test_assays_dict)

for assay in test_assays:
    task_df = ecfp_df[[assay, 'mol']].dropna()
    task_df.columns = ['y', 'mol'] # y is the target and mol is the molecular embedding (in this case ECFP)

    # show_df(task_df)

    test_assays_dict[assay] = task_df

print("\nPrinting the length of the DataFrame for each assay (in the testing set)...")
for assay, assay_df in test_assays_dict.items():
    print(f"Assay: '{assay}' - DataFrame size: '{len(assay_df)}'")

print("\nPrinting active/inactive counts for each assay (in the testing set)...")
for assay, assay_df in test_assays_dict.items():
    assay_value_counts = assay_df["y"].value_counts()
    active_count = assay_value_counts.get(1.0, 0)
    inactive_count = assay_value_counts.get(0.0, 0)

    print(f"Assay: '{assay}'; Active: '{active_count}'; Inactive: '{inactive_count}'")

Testing assays dictionary: {'MUV-832': None, 'MUV-846': None, 'MUV-852': None, 'MUV-858': None, 'MUV-859': None}

Printing the length of the DataFrame for each assay (in the testing set)...
Assay: 'MUV-832' - DataFrame size: '14667'
Assay: 'MUV-846' - DataFrame size: '14711'
Assay: 'MUV-852' - DataFrame size: '14651'
Assay: 'MUV-858' - DataFrame size: '14774'
Assay: 'MUV-859' - DataFrame size: '14746'

Printing active/inactive counts for each assay (in the testing set)...
Assay: 'MUV-832'; Active: '30'; Inactive: '14637'
Assay: 'MUV-846'; Active: '30'; Inactive: '14681'
Assay: 'MUV-852'; Active: '29'; Inactive: '14622'
Assay: 'MUV-858'; Active: '29'; Inactive: '14745'
Assay: 'MUV-859'; Active: '24'; Inactive: '14722'

### DGL

In [8]:
dgl_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.DGL)
show_df(dgl_df)

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles,mol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C,"Graph(num_nodes=26, num_edges=86,\n ndata..."
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1,"Graph(num_nodes=24, num_edges=76,\n ndata..."
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...,"Graph(num_nodes=34, num_edges=112,\n ndat..."
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...,"Graph(num_nodes=27, num_edges=87,\n ndata..."
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O,"Graph(num_nodes=15, num_edges=45,\n ndata..."
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID2999671,CCn1c(CSc2nccn2C)nc2cc(C(=O)O)ccc21,"Graph(num_nodes=22, num_edges=70,\n ndata..."
6,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,CID5390007,CCc1cccc2c1NC(=O)C21C2C(=O)N(Cc3ccccc3)C(=O)C2...,"Graph(num_nodes=31, num_edges=103,\n ndat..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CID5390006,COc1ccc(C2C(C(=O)NCc3ccccc3)=C(C)N=C3N=CNN32)c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."
8,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999674,CCCc1cc(=O)nc(SCC(=O)N(CC(C)C)C2CCS(=O)(=O)C2)...,"Graph(num_nodes=26, num_edges=80,\n ndata..."
9,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999675,CCn1cnc2c1c(=O)n(CC(=O)Nc1cc(C)on1)c(=O)n2Cc1c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."

Get the testing tasks (assays) depending on the dataset.

In [9]:
test_assays = test_assays_map.get(dataset_source)
print("Test assays for MUV dataset source:", test_assays)

Test assays for MUV dataset source: ['MUV-832', 'MUV-846', 'MUV-852', 'MUV-858', 'MUV-859']

Get the training tasks (assays) by getting the rest of assays that are not inside the testing set.

In [10]:
columns_to_drop = test_assays.copy()
columns_to_drop.extend(["mol_id", "smiles", "mol"])
print("Columns to drop:", columns_to_drop)

train_assays = [x for x in list(dgl_df.columns) if x not in columns_to_drop]
print("Training assays for MUV dataset:", train_assays)

Columns to drop: ['MUV-832', 'MUV-846', 'MUV-852', 'MUV-858', 'MUV-859', 'mol_id', 'smiles', 'mol']
Training assays for MUV dataset: ['MUV-466', 'MUV-548', 'MUV-600', 'MUV-644', 'MUV-652', 'MUV-689', 'MUV-692', 'MUV-712', 'MUV-713', 'MUV-733', 'MUV-737', 'MUV-810']

For each assay in the training set, filter out NULLs (NULLs mean that there was no test against that assay for that particular molecule).

In [11]:
train_assays_dict = dict.fromkeys(train_assays)
print("Training assays dictionary:", train_assays_dict)

for assay in train_assays:
    task_df = dgl_df[[assay, 'mol']].dropna()
    task_df.columns = ['y', 'mol'] # y is the target and mol is the molecular embedding (in this case ECFP)

    # show_df(task_df)

    train_assays_dict[assay] = task_df

print("\nPrinting the length of the DataFrame for each assay (in the training set)...")
for assay, assay_df in train_assays_dict.items():
    print(f"Assay: '{assay}' - DataFrame size: '{len(assay_df)}'")

print("\nPrinting active/inactive counts for each assay (in the training set)...")
for assay, assay_df in train_assays_dict.items():
    assay_value_counts = assay_df["y"].value_counts()
    active_count = assay_value_counts.get(1.0, 0)
    inactive_count = assay_value_counts.get(0.0, 0)

    print(f"Assay: '{assay}'; Active: '{active_count}'; Inactive: '{inactive_count}'")

# additional step when compare with the ECFP fingerpting but only for display purposes
feat_length = dgl_df.iloc[0].mol.ndata['feats'].shape[-1]
print("\nFeature length", feat_length)

Training assays dictionary: {'MUV-466': None, 'MUV-548': None, 'MUV-600': None, 'MUV-644': None, 'MUV-652': None, 'MUV-689': None, 'MUV-692': None, 'MUV-712': None, 'MUV-713': None, 'MUV-733': None, 'MUV-737': None, 'MUV-810': None}

Printing the length of the DataFrame for each assay (in the training set)...
Assay: 'MUV-466' - DataFrame size: '14841'
Assay: 'MUV-548' - DataFrame size: '14734'
Assay: 'MUV-600' - DataFrame size: '14728'
Assay: 'MUV-644' - DataFrame size: '14623'
Assay: 'MUV-652' - DataFrame size: '14902'
Assay: 'MUV-689' - DataFrame size: '14601'
Assay: 'MUV-692' - DataFrame size: '14644'
Assay: 'MUV-712' - DataFrame size: '14411'
Assay: 'MUV-713' - DataFrame size: '14836'
Assay: 'MUV-733' - DataFrame size: '14682'
Assay: 'MUV-737' - DataFrame size: '14691'
Assay: 'MUV-810' - DataFrame size: '14644'

Printing active/inactive counts for each assay (in the training set)...
Assay: 'MUV-466'; Active: '27'; Inactive: '14814'
Assay: 'MUV-548'; Active: '29'; Inactive: '14705'
Assay: 'MUV-600'; Active: '30'; Inactive: '14698'
Assay: 'MUV-644'; Active: '30'; Inactive: '14593'
Assay: 'MUV-652'; Active: '29'; Inactive: '14873'
Assay: 'MUV-689'; Active: '29'; Inactive: '14572'
Assay: 'MUV-692'; Active: '30'; Inactive: '14614'
Assay: 'MUV-712'; Active: '28'; Inactive: '14383'
Assay: 'MUV-713'; Active: '29'; Inactive: '14807'
Assay: 'MUV-733'; Active: '28'; Inactive: '14654'
Assay: 'MUV-737'; Active: '29'; Inactive: '14662'
Assay: 'MUV-810'; Active: '29'; Inactive: '14615'

Feature length 177

And do the same for the assays in the test set.

In [12]:
test_assays_dict = dict.fromkeys(test_assays)
print("Testing assays dictionary:", test_assays_dict)

for assay in test_assays:
    task_df = dgl_df[[assay, 'mol']].dropna()
    task_df.columns = ['y', 'mol'] # y is the target and mol is the molecular embedding (in this case ECFP)

    # show_df(task_df)

    test_assays_dict[assay] = task_df

print("\nPrinting the length of the DataFrame for each assay (in the testing set)...")
for assay, assay_df in test_assays_dict.items():
    print(f"Assay: '{assay}' - DataFrame size: '{len(assay_df)}'")

print("\nPrinting active/inactive counts for each assay (in the testing set)...")
for assay, assay_df in test_assays_dict.items():
    assay_value_counts = assay_df["y"].value_counts()
    active_count = assay_value_counts.get(1.0, 0)
    inactive_count = assay_value_counts.get(0.0, 0)

    print(f"Assay: '{assay}'; Active: '{active_count}'; Inactive: '{inactive_count}'")

Testing assays dictionary: {'MUV-832': None, 'MUV-846': None, 'MUV-852': None, 'MUV-858': None, 'MUV-859': None}

Printing the length of the DataFrame for each assay (in the testing set)...
Assay: 'MUV-832' - DataFrame size: '14667'
Assay: 'MUV-846' - DataFrame size: '14711'
Assay: 'MUV-852' - DataFrame size: '14651'
Assay: 'MUV-858' - DataFrame size: '14774'
Assay: 'MUV-859' - DataFrame size: '14746'

Printing active/inactive counts for each assay (in the testing set)...
Assay: 'MUV-832'; Active: '30'; Inactive: '14637'
Assay: 'MUV-846'; Active: '30'; Inactive: '14681'
Assay: 'MUV-852'; Active: '29'; Inactive: '14622'
Assay: 'MUV-858'; Active: '29'; Inactive: '14745'
Assay: 'MUV-859'; Active: '24'; Inactive: '14722'

### DGL (Bonds)

In [13]:
dgl_bonds_df = handler.load_processed_dataset(dataset_source=dataset_source, feature_type=FeatureType.DGL_WITH_BONDS)
show_df(dgl_bonds_df)

,MUV-466,MUV-548,MUV-600,MUV-644,MUV-652,MUV-689,MUV-692,MUV-712,MUV-713,MUV-733,MUV-737,MUV-810,MUV-832,MUV-846,MUV-852,MUV-858,MUV-859,mol_id,smiles,mol
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,CID2999678,Cc1cccc(N2CCN(C(=O)C34CC5CC(CC(C5)C3)C4)CC2)c1C,"Graph(num_nodes=26, num_edges=86,\n ndata..."
1,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,0.0,CID2999679,Cn1ccnc1SCC(=O)Nc1ccc(Oc2ccccc2)cc1,"Graph(num_nodes=24, num_edges=76,\n ndata..."
2,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CID2999672,COc1cc2c(cc1NC(=O)CN1C(=O)NC3(CCc4ccccc43)C1=O...,"Graph(num_nodes=34, num_edges=112,\n ndat..."
3,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID5390002,O=C1/C(=C/NC2CCS(=O)(=O)C2)c2ccccc2C(=O)N1c1cc...,"Graph(num_nodes=27, num_edges=87,\n ndata..."
4,0.0,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999670,NC(=O)NC(Cc1ccccc1)C(=O)O,"Graph(num_nodes=15, num_edges=45,\n ndata..."
5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,CID2999671,CCn1c(CSc2nccn2C)nc2cc(C(=O)O)ccc21,"Graph(num_nodes=22, num_edges=70,\n ndata..."
6,NaN,NaN,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,CID5390007,CCc1cccc2c1NC(=O)C21C2C(=O)N(Cc3ccccc3)C(=O)C2...,"Graph(num_nodes=31, num_edges=103,\n ndat..."
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,CID5390006,COc1ccc(C2C(C(=O)NCc3ccccc3)=C(C)N=C3N=CNN32)c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."
8,NaN,0.0,NaN,NaN,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999674,CCCc1cc(=O)nc(SCC(=O)N(CC(C)C)C2CCS(=O)(=O)C2)...,"Graph(num_nodes=26, num_edges=80,\n ndata..."
9,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CID2999675,CCn1cnc2c1c(=O)n(CC(=O)Nc1cc(C)on1)c(=O)n2Cc1c...,"Graph(num_nodes=30, num_edges=96,\n ndata..."

Get the testing tasks (assays) depending on the dataset.

In [14]:
test_assays = test_assays_map.get(dataset_source)
print("Test assays for MUV dataset source:", test_assays)

Test assays for MUV dataset source: ['MUV-832', 'MUV-846', 'MUV-852', 'MUV-858', 'MUV-859']

Get the training tasks (assays) by getting the rest of assays that are not inside the testing set.

In [15]:
columns_to_drop = test_assays.copy()
columns_to_drop.extend(["mol_id", "smiles", "mol"])
print("Columns to drop:", columns_to_drop)

train_assays = [x for x in list(dgl_bonds_df.columns) if x not in columns_to_drop]
print("Training assays for MUV dataset:", train_assays)

Columns to drop: ['MUV-832', 'MUV-846', 'MUV-852', 'MUV-858', 'MUV-859', 'mol_id', 'smiles', 'mol']
Training assays for MUV dataset: ['MUV-466', 'MUV-548', 'MUV-600', 'MUV-644', 'MUV-652', 'MUV-689', 'MUV-692', 'MUV-712', 'MUV-713', 'MUV-733', 'MUV-737', 'MUV-810']

For each assay in the training set, filter out NULLs (NULLs mean that there was no test against that assay for that particular molecule).

In [16]:
train_assays_dict = dict.fromkeys(train_assays)
print("Training assays dictionary:", train_assays_dict)

for assay in train_assays:
    task_df = dgl_bonds_df[[assay, 'mol']].dropna()
    task_df.columns = ['y', 'mol'] # y is the target and mol is the molecular embedding (in this case ECFP)

    # show_df(task_df)

    # additional step when compared with the ECFP/DGL
    # although seems to be redundant as nothing is really dropped (in the case of MUV)
    for index, r in task_df.iterrows():
        if r.mol.edata['edge_feats'].shape[-1] < 17:
            print("Dropping mol", r.mol)
            task_df.drop(index, inplace=True)

    train_assays_dict[assay] = task_df

print("\nPrinting the length of the DataFrame for each assay (in the training set)...")
for assay, assay_df in train_assays_dict.items():
    print(f"Assay: '{assay}' - DataFrame size: '{len(assay_df)}'")

print("\nPrinting active/inactive counts for each assay (in the training set)...")
for assay, assay_df in train_assays_dict.items():
    assay_value_counts = assay_df["y"].value_counts()
    active_count = assay_value_counts.get(1.0, 0)
    inactive_count = assay_value_counts.get(0.0, 0)

    print(f"Assay: '{assay}'; Active: '{active_count}'; Inactive: '{inactive_count}'")

node_feat_length = dgl_bonds_df.iloc[0].mol.ndata['feats'].shape[-1]
print("(Node) feature length", node_feat_length)

edge_feat_length = dgl_bonds_df.iloc[0].mol.edata['edge_feats'].shape[-1]
print("(Edge) feature length", edge_feat_length)

Training assays dictionary: {'MUV-466': None, 'MUV-548': None, 'MUV-600': None, 'MUV-644': None, 'MUV-652': None, 'MUV-689': None, 'MUV-692': None, 'MUV-712': None, 'MUV-713': None, 'MUV-733': None, 'MUV-737': None, 'MUV-810': None}

Printing the length of the DataFrame for each assay (in the training set)...
Assay: 'MUV-466' - DataFrame size: '14841'
Assay: 'MUV-548' - DataFrame size: '14734'
Assay: 'MUV-600' - DataFrame size: '14728'
Assay: 'MUV-644' - DataFrame size: '14623'
Assay: 'MUV-652' - DataFrame size: '14902'
Assay: 'MUV-689' - DataFrame size: '14601'
Assay: 'MUV-692' - DataFrame size: '14644'
Assay: 'MUV-712' - DataFrame size: '14411'
Assay: 'MUV-713' - DataFrame size: '14836'
Assay: 'MUV-733' - DataFrame size: '14682'
Assay: 'MUV-737' - DataFrame size: '14691'
Assay: 'MUV-810' - DataFrame size: '14644'

Printing active/inactive counts for each assay (in the training set)...
Assay: 'MUV-466'; Active: '27'; Inactive: '14814'
Assay: 'MUV-548'; Active: '29'; Inactive: '14705'
Assay: 'MUV-600'; Active: '30'; Inactive: '14698'
Assay: 'MUV-644'; Active: '30'; Inactive: '14593'
Assay: 'MUV-652'; Active: '29'; Inactive: '14873'
Assay: 'MUV-689'; Active: '29'; Inactive: '14572'
Assay: 'MUV-692'; Active: '30'; Inactive: '14614'
Assay: 'MUV-712'; Active: '28'; Inactive: '14383'
Assay: 'MUV-713'; Active: '29'; Inactive: '14807'
Assay: 'MUV-733'; Active: '28'; Inactive: '14654'
Assay: 'MUV-737'; Active: '29'; Inactive: '14662'
Assay: 'MUV-810'; Active: '29'; Inactive: '14615'
(Node) feature length 177
(Edge) feature length 17

And do the same for the assays in the test set.

In [17]:
test_assays_dict = dict.fromkeys(test_assays)
print("Testing assays dictionary:", test_assays_dict)

for assay in test_assays:
    task_df = dgl_bonds_df[[assay, 'mol']].dropna()
    task_df.columns = ['y', 'mol'] # y is the target and mol is the molecular embedding (in this case ECFP)

    # show_df(task_df)

    # additional step when compared with the ECFP/DGL
    # although seems to be redundant as nothing is really dropped (in the case of MUV)
    for index, r in dgl_bonds_df.iterrows():
        if r.mol.edata['edge_feats'].shape[-1] < 17:
            print("Dropping mol", r.mol)
            dgl_bonds_df.drop(index, inplace=True)

    test_assays_dict[assay] = task_df

print("\nPrinting the length of the DataFrame for each assay (in the testing set)...")
for assay, assay_df in test_assays_dict.items():
    print(f"Assay: '{assay}' - DataFrame size: '{len(assay_df)}'")

print("\nPrinting active/inactive counts for each assay (in the testing set)...")
for assay, assay_df in test_assays_dict.items():
    assay_value_counts = assay_df["y"].value_counts()
    active_count = assay_value_counts.get(1.0, 0)
    inactive_count = assay_value_counts.get(0.0, 0)

    print(f"Assay: '{assay}'; Active: '{active_count}'; Inactive: '{inactive_count}'")

Testing assays dictionary: {'MUV-832': None, 'MUV-846': None, 'MUV-852': None, 'MUV-858': None, 'MUV-859': None}

Printing the length of the DataFrame for each assay (in the testing set)...
Assay: 'MUV-832' - DataFrame size: '14667'
Assay: 'MUV-846' - DataFrame size: '14711'
Assay: 'MUV-852' - DataFrame size: '14651'
Assay: 'MUV-858' - DataFrame size: '14774'
Assay: 'MUV-859' - DataFrame size: '14746'

Printing active/inactive counts for each assay (in the testing set)...
Assay: 'MUV-832'; Active: '30'; Inactive: '14637'
Assay: 'MUV-846'; Active: '30'; Inactive: '14681'
Assay: 'MUV-852'; Active: '29'; Inactive: '14622'
Assay: 'MUV-858'; Active: '29'; Inactive: '14745'
Assay: 'MUV-859'; Active: '24'; Inactive: '14722'